# Generated by Django 3.1.2 on 2020-10-29 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_system', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
